/*
Doc Box API

<- The intent of this API is to provide a consistent/standardized mechanism to create new documents, delete existing documents, retrieving information about uploaded documents. This Specification is based on TMF667 - Document Management Release 17.0.1 from November 2017.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmf

import (
	"encoding/json"
)

// HALSelfLink Hyperlink reference to the resource itself.
type HALSelfLink struct {
	// URI reference to the resource itself.
	Href string `json:"href"`
}

// NewHALSelfLink instantiates a new HALSelfLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHALSelfLink(href string) *HALSelfLink {
	this := HALSelfLink{}
	this.Href = href
	return &this
}

// NewHALSelfLinkWithDefaults instantiates a new HALSelfLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHALSelfLinkWithDefaults() *HALSelfLink {
	this := HALSelfLink{}
	return &this
}

// GetHref returns the Href field value
func (o *HALSelfLink) GetHref() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Href
}

// GetHrefOk returns a tuple with the Href field value
// and a boolean to check if the value has been set.
func (o *HALSelfLink) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Href, true
}

// SetHref sets field value
func (o *HALSelfLink) SetHref(v string) {
	o.Href = v
}

func (o HALSelfLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["href"] = o.Href
	}
	return json.Marshal(toSerialize)
}

type NullableHALSelfLink struct {
	value *HALSelfLink
	isSet bool
}

func (v NullableHALSelfLink) Get() *HALSelfLink {
	return v.value
}

func (v *NullableHALSelfLink) Set(val *HALSelfLink) {
	v.value = val
	v.isSet = true
}

func (v NullableHALSelfLink) IsSet() bool {
	return v.isSet
}

func (v *NullableHALSelfLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHALSelfLink(val *HALSelfLink) *NullableHALSelfLink {
	return &NullableHALSelfLink{value: val, isSet: true}
}

func (v NullableHALSelfLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHALSelfLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
